name: Daily WhatsApp Sender

on:
  schedule:
    # Run at 02:29 UTC (which is 06:29 AM UTC+4)
    - cron: '29 2 * * *'
  workflow_dispatch: # Allow manual trigger button

jobs:
  run-sender:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Sender Script
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PHONE_NUMBER_ID: ${{ secrets.PHONE_NUMBER_ID }}
      run: |
        python run_job.py
